#!/usr/bin/env bash
# Governance Dashboard Cron Installer (P92 B) — DEPRECATED
#
# .. deprecated::
#     Cron jobs should use omo CLI directly:
#         omo doctor           # 统一健康检查
#         omo inspect          # 统一检查
#
# 安装 governance dashboard 14 工具统一巡检 cron 到系统 crontab
# 配合 P90 governance-dashboard-crontab (每日 6:00 + 每周一 7:00)
#
# 用法:
#   ./scripts/omo/install-dashboard-cron.sh              # 默认安装
#   ./scripts/omo/install-dashboard-cron.sh --uninstall  # 移除
#   ./scripts/omo/install-dashboard-cron.sh --dry-run    # 只显示
#   ./scripts/omo/install-dashboard-cron.sh --status     # 查看状态
#
# 守护契约:
#   - 永不破坏已有 crontab (标记 + 隔离块)
#   - 标记块用 GOV_DASHBOARD_BEGIN / END 包裹
#   - 重复运行 idempotent (重复安装只覆盖标记块)
#   - 与 X2 freshness cron 隔离 (不同标记块)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CRONTAB_FILE="$WORKSPACE_ROOT/.omo/cron/governance-dashboard-crontab"
MARKER_BEGIN="# >>> GOV_DASHBOARD_BEGIN >>>"
MARKER_END="# <<< GOV_DASHBOARD_END <<<"

ACTION="install"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --uninstall) ACTION="uninstall" ;;
    --dry-run)   ACTION="install-dry-run" ;;
    --status)    ACTION="status" ;;
    -h|--help)
      sed -n '2,18p' "$0"
      exit 0
      ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
  shift
done

case "$ACTION" in
  status)
    echo "=== Current governance dashboard crontab state ==="
    if crontab -l 2>/dev/null | grep -q "$MARKER_BEGIN"; then
      echo "INSTALLED"
      crontab -l 2>/dev/null | awk "/$MARKER_BEGIN/,/$MARKER_END/"
    else
      echo "NOT INSTALLED"
    fi
    ;;

  install-dry-run)
    echo "=== DRY RUN: would install ==="
    echo "Crontab file: $CRONTAB_FILE"
    echo "Marker: $MARKER_BEGIN ... $MARKER_END"
    echo "---"
    cat "$CRONTAB_FILE"
    ;;

  install)
    if [[ ! -f "$CRONTAB_FILE" ]]; then
      echo "❌ Crontab file not found: $CRONTAB_FILE"
      exit 1
    fi
    echo "=== Installing governance dashboard cron ==="
    echo "Workspace: $WORKSPACE_ROOT"
    echo "Crontab file: $CRONTAB_FILE"
    BACKUP_FILE="$WORKSPACE_ROOT/.omo/cron/crontab-backup-$(date +%Y%m%d-%H%M%S).txt"
    if crontab -l >/dev/null 2>&1; then
      crontab -l > "$BACKUP_FILE" 2>/dev/null || true
      echo "Backup current crontab: $BACKUP_FILE"
    fi
    EXISTING_CRON=$(crontab -l 2>/dev/null || echo "")
    FILTERED_CRON=$(echo "$EXISTING_CRON" | awk -v begin="$MARKER_BEGIN" -v end="$MARKER_END" '
      $0 == begin { in_block = 1; next }
      $0 == end { in_block = 0; next }
      !in_block { print }
    ')
    NEW_CRON="$FILTERED_CRON"
    NEW_CRON="$NEW_CRON$MARKER_BEGIN"
    NEW_CRON="$NEW_CRON"$'\n'"# Auto-generated by install-dashboard-cron.sh (P92 B)"
    while IFS= read -r line; do
      NEW_CRON="$NEW_CRON"$'\n'"$line"
    done < "$CRONTAB_FILE"
    NEW_CRON="$NEW_CRON"$'\n'"$MARKER_END"
    echo "$NEW_CRON" | crontab -
    echo "✅ Installed. Verify: crontab -l | grep '$MARKER_BEGIN'"
    ;;

  uninstall)
    echo "=== Uninstalling governance dashboard cron ==="
    if crontab -l 2>/dev/null | grep -q "$MARKER_BEGIN"; then
      EXISTING_CRON=$(crontab -l 2>/dev/null || echo "")
      FILTERED_CRON=$(echo "$EXISTING_CRON" | awk -v begin="$MARKER_BEGIN" -v end="$MARKER_END" '
        $0 == begin { in_block = 1; next }
        $0 == end { in_block = 0; next }
        !in_block { print }
      ')
      echo "$FILTERED_CRON" | crontab -
      echo "✅ Uninstalled."
    else
      echo "Not installed (no marker found), nothing to do."
    fi
    ;;

  *)
    echo "Unknown ACTION: $ACTION" >&2
    exit 1
    ;;
esac
