#!/usr/bin/env bash
# X2 Freshness Cron Installer (P44 R0) — DEPRECATED
#
# .. deprecated::
#     Cron jobs should use omo CLI directly:
#         omo audit freshness  # X2 freshness 巡检
#
# 安装 X2 freshness 巡检 cron 到系统 crontab
#
# 用法:
#   ./scripts/omo/install-x2-cron.sh              # 默认安装到 crontab
#   ./scripts/omo/install-x2-cron.sh --uninstall  # 移除
#   ./scripts/omo/install-x2-cron.sh --dry-run    # 只显示不真安装
#   ./scripts/omo/install-x2-cron.sh --status     # 查看当前安装状态
#
# 守护契约:
#   - 永不破坏已有 crontab (标记 + 隔离块)
#   - 标记块用 X2_FRESHNESS_AUDIT_BEGIN / END 包裹
#   - 重复运行 idempotent (重复安装只覆盖标记块)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CRONTAB_FILE="$WORKSPACE_ROOT/.omo/cron/x2-freshness-crontab"
MARKER_BEGIN="# >>> X2_FRESHNESS_AUDIT_BEGIN >>>"
MARKER_END="# <<< X2_FRESHNESS_AUDIT_END <<<"

ACTION="install"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --uninstall) ACTION="uninstall" ;;
    --dry-run)   ACTION="install-dry-run" ;;
    --status)    ACTION="status" ;;
    -h|--help)
      sed -n '2,18p' "$0"
      exit 0
      ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
  shift
done

case "$ACTION" in
  status)
    echo "=== Current X2 freshness crontab state ==="
    if crontab -l 2>/dev/null | grep -q "$MARKER_BEGIN"; then
      echo "INSTALLED"
      crontab -l 2>/dev/null | awk "/$MARKER_BEGIN/,/$MARKER_END/"
    else
      echo "NOT INSTALLED"
    fi
    ;;

  install-dry-run)
    echo "=== DRY RUN: would install ==="
    echo "Crontab file: $CRONTAB_FILE"
    echo "Marker: $MARKER_BEGIN ... $MARKER_END"
    echo "---"
    cat "$CRONTAB_FILE"
    ;;

  install)
    if crontab -l 2>/dev/null | grep -q "$MARKER_BEGIN"; then
      echo "X2 freshness crontab already installed, replacing block"
      # 移除旧标记块
      crontab -l 2>/dev/null | awk -v begin="$MARKER_BEGIN" -v end="$MARKER_END" \
        '$0 != begin && $0 != end' > /tmp/crontab.new
    else
      crontab -l 2>/dev/null > /tmp/crontab.new || true
    fi

    {
      echo "$MARKER_BEGIN"
      echo "# Generated by install-x2-cron.sh on $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
      cat "$CRONTAB_FILE"
      echo "$MARKER_END"
    } >> /tmp/crontab.new

    crontab /tmp/crontab.new
    rm -f /tmp/crontab.new
    echo "✅ X2 freshness crontab installed."
    echo "   Verify with: crontab -l | grep X2_FRESHNESS_AUDIT"
    echo "   Or run: $0 --status"
    ;;

  uninstall)
    if ! crontab -l 2>/dev/null | grep -q "$MARKER_BEGIN"; then
      echo "X2 freshness crontab NOT installed, nothing to do"
      exit 0
    fi
    crontab -l 2>/dev/null | awk -v begin="$MARKER_BEGIN" -v end="$MARKER_END" \
      '$0 != begin && $0 != end' > /tmp/crontab.new
    crontab /tmp/crontab.new
    rm -f /tmp/crontab.new
    echo "✅ X2 freshness crontab removed."
    ;;
esac